package com.example.agreement.entity.enumerated;

public enum EvidenceAction {
    CONTRACT_CREATED,
    CONTRACT_ACCEPTED,
    PAYMENT_LATE,
    CONTRACT_SUSPENDED,
    CONTRACT_CLOSED,
    PAYMENT_CONFIRMED,
    PAYMENT_CLAIMED,
    PAYMENT_PAID,
    PAYMENT_REJECTED,
    RENTER_SUBMITTED_INFO,
    OWNER_APPROVED_CONTRACT
}